import { redirect } from "next/navigation";
import Link from "next/link";
import { Suspense } from "react";
import prisma from "@/lib/db";
import { getSession } from "@/lib/session";
import PageHeader from "@/components/ui/PageHeader";
import StatusBadge from "@/components/ui/StatusBadge";
import ReportFilters from "./ReportFilters";
import ExportButton from "./ExportButton";

export const metadata = { title: "Reports - Tax Invoice History - Iruka Motors" };

function formatCurrency(amount: number) {
  return `Rs. ${amount.toLocaleString("en-LK", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

type SearchParams = Promise<{
  search?: string;
  payment?: string;
  mode?: string;
  from?: string;
}>;

export default async function AdminReportsPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (session.role !== "ADMIN") redirect("/dashboard/employee");

  const allInvoices = await prisma.taxInvoice.findMany({
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      taxInvoiceNo: true,
      invoiceDate: true,
      purchaserName: true,
      paymentMode: true,
      placeOfSupply: true,
      totalAmount: true,
      isPaid: true,
      invoiceData: true,
      createdAt: true,
      user: {
        select: {
          id: true,
          name: true,
          email: true,
        },
      },
    },
  });

  // Normalise rows — extract fields that may be in invoiceData JSON for older records
  const allRows = allInvoices.map((inv) => {
    const data = inv.invoiceData as {
      placeOfSupply?: string;
      purchaserName?: string;
      additionalInfo?: string;
    } | null;
    return {
      ...inv,
      placeOfSupply: inv.placeOfSupply || (data?.placeOfSupply ?? null),
      purchaserName: inv.purchaserName || (data?.purchaserName ?? null),
      additionalInfo: data?.additionalInfo ?? null,
    };
  });

  // Unique payment modes for filter dropdown
  const paymentModes = Array.from(
    new Set(allRows.map((r) => r.paymentMode).filter(Boolean) as string[])
  );

  // Apply filters from URL search params
  const { search = "", payment = "", mode = "", from = "" } = await searchParams;

  const rows = allRows.filter((inv) => {
    if (search) {
      const q = search.toLowerCase();
      const matchNo       = inv.taxInvoiceNo.toLowerCase().includes(q);
      const matchPurchaser = (inv.purchaserName ?? "").toLowerCase().includes(q);
      const matchSupply   = (inv.placeOfSupply ?? "").toLowerCase().includes(q);
      const matchEmployee = (inv.user.name ?? "").toLowerCase().includes(q);
      const matchEmail    = (inv.user.email ?? "").toLowerCase().includes(q);
      if (!matchNo && !matchPurchaser && !matchSupply && !matchEmployee && !matchEmail) return false;
    }
    if (payment === "paid"   && !inv.isPaid) return false;
    if (payment === "unpaid" &&  inv.isPaid) return false;
    if (mode && inv.paymentMode !== mode) return false;
    if (from) {
      const invDate = inv.invoiceDate.toISOString().split("T")[0];
      if (invDate !== from) return false;
    }
    return true;
  });

  const totalRevenue = rows.reduce((sum, inv) => sum + inv.totalAmount, 0);

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <div className="px-8 pb-6 pt-8">
        <PageHeader
          title="Tax Invoice Reports"
          subtitle="History of tax invoices generated by all employees"
        />
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-1 gap-4 px-8 pb-6 md:grid-cols-2">
        <div className="rounded-xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">
            {search || payment || mode || from ? "Filtered Invoices" : "Total Invoices"}
          </p>
          <p className="mt-1 text-3xl font-semibold text-foreground">{rows.length}</p>
        </div>
        <div className="rounded-xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">
            {search || payment || mode || from ? "Filtered Revenue (incl. VAT)" : "Total Revenue (incl. VAT)"}
          </p>
          <p className="mt-1 text-3xl font-semibold text-foreground">{formatCurrency(totalRevenue)}</p>
        </div>
      </div>

      <div className="flex-1 px-8 pb-8">
        {allInvoices.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center">
            <h2 className="text-lg font-semibold text-foreground">No tax invoices found</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Once employees generate invoices, they will appear here.
            </p>
          </div>
        ) : (
          <>
            <Suspense>
              <ReportFilters
                paymentModes={paymentModes}
                total={allRows.length}
                filtered={rows.length}
              />
            </Suspense>

            <div className="mb-4 flex justify-end">
              <ExportButton
                rows={rows.map((r) => ({
                  taxInvoiceNo: r.taxInvoiceNo,
                  invoiceDate: r.invoiceDate.toISOString().split("T")[0],
                  placeOfSupply: r.placeOfSupply ?? null,
                  paymentMode: r.paymentMode ?? null,
                  totalAmount: r.totalAmount,
                  isPaid: r.isPaid,
                  additionalInfo: r.additionalInfo ?? null,
                }))}
              />
            </div>

            {rows.length === 0 ? (
              <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center">
                <h2 className="text-lg font-semibold text-foreground">No invoices match your filters</h2>
                <p className="mt-2 text-sm text-muted-foreground">
                  Try adjusting or clearing the filters above.
                </p>
              </div>
            ) : (
              <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
                <div className="overflow-x-auto">
                  <table className="w-full min-w-220">
                    <thead className="bg-muted/50 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      <tr>
                        <th className="px-5 py-4">Invoice No.</th>
                        <th className="px-5 py-4">Invoice Date</th>
                        <th className="px-5 py-4">Place of Supply</th>
                        <th className="px-5 py-4">Employee</th>
                        <th className="px-5 py-4">Employee Email</th>
                        <th className="px-5 py-4">Purchaser</th>
                        <th className="px-5 py-4">Payment Mode</th>
                        <th className="px-5 py-4">Total</th>
                        <th className="px-5 py-4">Saved At</th>
                        <th className="px-5 py-4">Status</th>
                        <th className="px-5 py-4">Payment</th>
                        <th className="px-5 py-4">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {rows.map((invoice) => (
                        <tr key={invoice.id} className="text-sm text-foreground hover:bg-muted/30">
                          <td className="px-5 py-4 font-medium">{invoice.taxInvoiceNo}</td>
                          <td className="px-5 py-4">{invoice.invoiceDate.toLocaleDateString("en-US")}</td>
                          <td className="px-5 py-4">
                            {invoice.placeOfSupply ? (
                              <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 border border-blue-200 px-2.5 py-1 text-xs font-semibold text-blue-700">
                                <svg className="w-3 h-3 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                                  <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7z" />
                                  <circle cx="12" cy="9" r="2.5" />
                                </svg>
                                {invoice.placeOfSupply}
                              </span>
                            ) : (
                              <span className="text-muted-foreground">—</span>
                            )}
                          </td>
                          <td className="px-5 py-4">{invoice.user.name}</td>
                          <td className="px-5 py-4 text-muted-foreground">{invoice.user.email}</td>
                          <td className="px-5 py-4">{invoice.purchaserName || "—"}</td>
                          <td className="px-5 py-4">{invoice.paymentMode || "—"}</td>
                          <td className="px-5 py-4 font-medium">{formatCurrency(invoice.totalAmount)}</td>
                          <td className="px-5 py-4 text-muted-foreground">{invoice.createdAt.toLocaleString("en-US")}</td>
                          <td className="px-5 py-4">
                            <StatusBadge label="Saved" variant="green" />
                          </td>
                          <td className="px-5 py-4">
                            {invoice.isPaid ? (
                              <StatusBadge label="Paid" variant="green" />
                            ) : (
                              <StatusBadge label="Unpaid" variant="red" />
                            )}
                          </td>
                          <td className="px-5 py-4">
                            <div className="flex items-center gap-2">
                              <Link
                                href={`/dashboard/admin/reports/${invoice.id}`}
                                className="inline-flex items-center rounded-lg border border-border px-3 py-1.5 text-xs font-medium text-foreground hover:bg-muted transition"
                              >
                                Show
                              </Link>
                              <Link
                                href={`/dashboard/admin/reports/${invoice.id}/print`}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="inline-flex items-center rounded-lg bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:opacity-90 transition"
                              >
                                Print
                              </Link>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
